---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
    - set_fact:
        login_banner_file: "{{ item }}"
      with_first_found:
        - files:
          - "{{ inventory_dir }}/host_data/{{ inventory_hostname }}/banner.txt"
          - "{{ inventory_dir }}/host_data/all/banner.txt"
          skip: true

    - name: configure the login banner
      net_banner:
        banner: "{{ 'motd' if ansible_network_os == 'nxos' else 'login' }}"
        text: "{{ lookup('file', login_banner_file) }}"
        state: present
      when: login_banner_file is defined

    - set_fact:
        motd_file: "{{ item }}"
      with_first_found:
        - files:
          - "{{ inventory_dir }}/host_data/{{ inventory_hostname }}/motd.txt"
          - "{{ inventory_dir }}/host_data/all/motd.txt"
          skip: true

    - name: configure the MOTD
      net_banner:
        banner: motd
        text: "{{ lookup('file', motd_file) }}"
        state: present
      when: motd_file is defined and ansible_network_os != 'nxos'
