---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
    - set_fact:
        net_hostname: "{{ inventory_hostname.split('.')[0] }}"
        net_domain_name: "{{ inventory_hostname.split('.')[1:] | join('.') }}"

    - debug: var=net_hostname
    - debug: var=net_domain_name

    - name: Set the system attributes
      net_system:
        hostname: "{{ net_hostname }}"
        domain_name: "{{ net_domain_name }}"
