---
- hosts: all
  connection: local
  gather_facts: no
  pre_tasks:
    - name: Load the vars file
      include_vars: "{{ item }}"
      with_first_found:
      - "{{ inventory_dir }}/host_data/{{ inventory_hostname }}/net-system-vars.yml"
      - "{{ inventory_dir }}/host_data/all/net-system-vars.yml"

  tasks:

    - set_fact:
        net_hostname: "{{ inventory_hostname.split('.')[0] }}"
        net_domain_name: "{{ inventory_hostname.split('.')[1:] | join('.') }}"

    - name: Set the system attributes
      net_system:
        hostname: "{{ net_hostname }}"
        domain_name: "{{ net_domain_name }}"

    - name: Set the name servers
      net_system:
        name_servers: "{{ site_name_servers }}"
      when: site_name_servers is defined

    - name: Set the domain search
      net_system:
        domain_search: "{{ site_domain_search }}"
      when: site_domain_search is defined
